package.json, shared/components/AppBar.jsx, shared/components/pages/ActivationPage.less, shared/components/pages/ActivationsPage.less
Remove horizontal scrollbar
Fix scroll events for app bar in Firefox and IE
=> Ticket 16635 & 16621: Fix scrolling bugs

etc/client-config.json.sample, shared/containers/pages/ActivationPage.jsx, shared/utils/apiResponseFormatter.js
1. sharedLink -> linkToPass
2. changed config itsquiz -> qas.itsquiz (newest API)
3. open link to pass the test in the same tab
=> Change field name sharedLink -> linkToPass & open test in the same tab

shared/components/pages/ActivationsPage.jsx, shared/components/pages/ActivationsPage.less, shared/containers/pages/ActivationPage.jsx, shared/containers/pages/ActivationsPage.jsx
Now Quiz Wall can be embedded with *?embed=true* param
=> Ticket 16699 : Add embed styling

shared/components/pages/ActivationsPage.jsx, shared/components/pages/ActivationsPage.less, shared/containers/pages/ActivationsPage.jsx
=> Ticket 16838 : Add text message if there no entities for activations page

server/app.js, server/utils.js, shared/components/AppBar.jsx, shared/components/AppBar.less, shared/components/LanguageSwitch.jsx, shared/components/LanguageSwitch.less, shared/components/pages/ActivationPage.jsx, shared/components/pages/ActivationPage.less, shared/containers/LanguageSwitch.jsx, shared/containers/layouts/MainLayout.jsx, shared/containers/pages/ActivationPage.jsx, shared/reducers/index.js, shared/utils/apiResponseFormatter.js, shared/utils/index.js
+ Do not display share button and display tag if activation is private
+ Add language switch
+ Remove redundant data from mail layout
+ Add more meta data (for twitter & facebook)
+ Change state structure for ```currentActivation``` 
+ Do not display the same activation in other author activations list
=> Ticket 16856 : 	Do not display share button and display tag if activation is private

etc/client-config.json.sample, package.json, server/app.js, shared/components/AppBar.jsx, shared/components/AppBar.less, shared/components/AppBarWithBackground.jsx, shared/components/LanguageSwitch.less, shared/components/SearchBox.less, shared/components/pages/ActivationPage.jsx, shared/components/pages/ActivationsPage.jsx, shared/components/pages/ActivationsPage.less, shared/containers/LanguageSwitch.jsx, shared/containers/pages/ActivationPage.jsx, shared/containers/pages/ActivationsPage.jsx, shared/i18n/Tools.js
Bug with language switch blinking still not fixed.
+ Fixed mobile version
=> T16882 : Add login link to Quiz wall

server/app.js, shared/components/AppBar.jsx, shared/components/AppBar.less, shared/components/LanguageSwitch.less, shared/components/SearchBox.less, shared/components/pages/ActivationPage.jsx, shared/components/pages/ActivationPage.less
+ Added normalize css
+ Add menu item for sign up
+ Fix view on mobile phones
+ Fix search box alignment
**Looks like this**
on desktop
on mobile
test page
on desktop
on mobile
=> Ticket 16965 : Add "Sign Up" button to Quiz Wall + fix alignment on mobile phones

etc/client-config.json.sample, server/app.js, shared/components/ShareDialog.jsx, shared/components/pages/ActivationPage.jsx, shared/components/pages/ActivationsPage.jsx, shared/containers/App.jsx, shared/containers/LanguageSwitch.jsx, shared/containers/ShareDialog.jsx, shared/containers/pages/ActivationPage.jsx, shared/containers/pages/ActivationsPage.jsx, shared/utils/googleAnalytics.js
+ Add google analytics
+ Create util for events
+ Small refactoring
+ Move share logic to container
=> Ticket 16967 : Google analytics

shared/components/Dialog.jsx, shared/components/Dialog.less, shared/components/WelcomeDialog.jsx, shared/components/WelcomeDialog.less
=> T17213 Fix welcome screen on mobile devices

shared/components/QuizCard.jsx, shared/components/QuizCard.less, shared/components/QuizTile.jsx, shared/components/QuizTile.less, shared/components/pages/ActivationsPage.jsx, shared/reducers/index.js
Add href for SEO (resolve #44)
=> Issue #44: href for SEO

shared/components/ExpandableText.jsx, shared/components/Markdown.jsx
=> 18187 - Quiz Wall: Слишком сильно обрезается длинная ссылка в описании

shared/components/ExpandableText.less
=> 18184 - Длинное описание, без пробелов,не влезает на экран (например ссылка)

bin/extract_lang.sh, bin/po2json.sh, lang/ru.po, lang/tr.po, lang/uk.po, public/static/lang/tr.json, server/app.js, server/utils.js, shared/utils/index.js
not ready don't merge.
thnx. :+1:
=> Turkish translate

lang/zh_cn.po, public/static/lang/zh_cn.json, server/app.js, shared/utils/index.js
=> add zh-cn translation

shared/components/pages/ActivationPage.jsx, shared/components/pages/ActivationPage.less, shared/utils/apiResponseFormatter.js
=> 17947 - Multiple passes of quiz by assignee (number of try and dueTime display)

shared/containers/App.jsx
Resolves problem with redirection to Quiz Wall, while already being on a page of any activation on Quiz Wall
=> 18420 - Handle message from UI - redirect to /activation

shared/components/pages/ActivationPage.jsx, shared/components/pages/ActivationPage.less, shared/utils/apiResponseFormatter.js
=> T18503 - Add custom grade display

shared/components/pages/ActivationPage.less
=> 18711 - Increase font-size of greeting phrase and breaks long greetings

shared/components/pages/ActivationPage.jsx, shared/components/pages/ActivationsPage.jsx, shared/components/pages/ActivationsPage.less
=> 19124 - Correct display of categories toolbar on mobile

package.json
=> add cross-env

server/app.js
Set Content-Type header.
Need for cypress.io
=> Cypress fix

server/app.js
=> Remove double quotes

shared/components/pages/ActivationPage.jsx
=> Fix eslint error
